### ISSUE TITLE
Build error: "primordials is not defined" Node.js-v12

### ISSUE THREAD

**Issue by viteos** [mulesoft-labs/api-console-cli#38] opened 2019-05-01 08:07 UTC
Error on `api-console build` Node.js-v12.x
`primordials is not defined`

**Comment by jarrodek** [comment] 2019-05-16 23:35
Hi,
Sorry for late response. I was on vacation.

Could you give a more context? I do not recognize `primordials` in the library.

**Comment by DanielRuf** [comment] 2019-05-31 06:30
This is referenced in `natives` / `graceful-fs`. Updating these or downgrading to Node < 12 should resolve this.

**Comment by jarrodek** [comment] 2019-05-31 18:38
Recently I've updated the module (mostly dependencies upgrades) and now I cannot reproduce this problem anymore.

Tested on:

MacOS 10.13.6
Node: v12.3.1

Win 10 Pro 1903
Node: v12.3.1 (CMD)
Node: v12.3.1 (PS)

Ubuntu 16.04 (Xenial) LTS
Node: v12.3.1

I am closing the issue as fixed but feel free to reopen if necessary.

**Closed by jarrodek** 2019-05-31 18:38 UTC
